#pragma once

using namespace ATL;

template <class T>
class CProxy_IfsXMLParserEvents : public IConnectionPointImpl<T, &__uuidof( _IfsXMLParserEvents ), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
